# exp
num_agents: 3
num_obstacles: 2
size_obstacle: 0.05
v_drone: 0.5
v_low: 1.3
v_high: 1.3
size: 0.7
# model_dir: /root/OmniDrones/scripts/outputs/2obstacle_size07_speed1_5_discrteaction_speedpenalty_catch015_loadspeed1_3/08-24_07-29/wandb/run-20230824_072914-umbsrc5r/files/checkpoint_2883846144.pt
model_dir: null
use_collision: 1
use_speed_penalty: 1
catch_radius: 0.15
collision_radius: 0.01

headless: true

sim: ${task.sim}
env: ${task.env}

total_frames: 250_000_000_000
max_iters: -1
eval_interval: 100
save_interval: 100
seed: 0

viewer:
  eye: [2, 2, 2]
  lookat: [0., 0., 0.]

wandb:
  group: ${oc.select:..task.name}
  run_name: 2obstacle_size07_speed1_3_discrteaction_speedpenalty_catch015
  # run_name: debug
  job_type: train
  entity: chenjy
  project: issac_drones
  mode: online # set to 'disabled' when debugging locally
  # mode: disabled
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  # - task: PlatformHover
  - task: PredatorPrey_debug
  - algo: mappo
  - _self_
