# exp
num_agents: 3
num_obstacles: 0
size_obstacle: 0.1
v_drone: 0.5
v_low: 1.3
v_high: 1.3
step: 0.02
# obstacles
actual_low: 0
actual_high: 1
use_load: 0
fixed_vel: 0
vel0: 1.3
test_list: 0
v_list: [1.3]
mixed: 0
obs: 0

catch_radius: 0.1


headless: true

sim: ${task.sim}
env: ${task.env}

total_frames: 250_000_000_000
max_iters: -1
eval_interval: 100
save_interval: -1
seed: 0

viewer:
  eye: [7.5, 7.5, 7.5]
  lookat: [0., 0., 0.]

wandb:
  group: ${oc.select:..task.name}
  run_name: ${oc.select:..task.name,test}-${oc.select:..algo.name,none}
  job_type: train
  entity: chenjy
  project: issac_drones
  mode: online # set to 'disabled' when debugging locally
  # mode: disabled
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  # - task: PlatformHover
  - task: PredatorPrey_debug
  - algo: mappo
  - _self_
