use_dynamic: 0

# exp
num_agents: 3
obstacle_size: 0.05
v_drone: 1.0
num_obstacles: 5
obstacle_control_fre: 20
# model_dir: /root/OmniDrones/scripts/outputs/5obstacle_size1_speed1_3_obstaclespeed0/09-15_07-10/wandb/run-20230915_071043-toc9dkyu/files/checkpoint_2792226816.pt
model_dir: null
use_collision: 1
use_speed_penalty: 1
catch_radius: 0.15
collision_radius: 0.01

headless: True

sim: ${task.sim}
env: ${task.env}

total_frames: 250_000_000_000
max_iters: -1
eval_interval: 100
save_interval: 100
seed: 0

viewer:
  eye: [2, 2, 2]
  lookat: [0., 0., 0.]

wandb:
  group: ${oc.select:..task.name}
  run_name: APF_RL
  # run_name: model_debug
  job_type: train
  entity: linster
  project: issac_drones
  # mode: online # set to 'disabled' when debugging locally
  mode: disabled
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: HideAndSeek_circle_eval
  - algo: mappo
  - _self_
