# model_dir: /home/chenjy/OmniDrones/scripts/outputs/random0to3_final/v2_0_catch0_2_height0_6_size0_9.pt
# model_dir: /home/chenjy/OmniDrones/scripts/outputs/final_results/DR_wovalidation/seed0/v1_6_catch0_2_height1_2_size0_9.pt
# model_dir: null
model_dir: /home/chenjy/OmniDrones/scripts/outputs/cl_v2_4_catch0_13.pt
# model_dir: /home/chenjy/OmniDrones/scripts/outputs/cl_fixed0_v2_4_catch0_16_load/04-20_15-59/wandb/run-20240420_155909-ecvvtdx7/files/checkpoint_26345472.pt

# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

total_frames: 100_000_000_000
max_iters: -1
eval_interval: 200
save_interval: 200
seed: 0

viewer:
  resolution: [960, 720]
  # up
  eye: [0.0, 0.0, 6.]
  lookat: [0.01, 0., 2.]
  # # front
  # eye: [2.5, 2.5, 4.0]
  # lookat: [0., 0., 0.7]

wandb:
  group: ${oc.select:..task.name}
  run_name: cl_wodistance_v2_4_catch0_125
  # run_name: check
  job_type: train
  entity: chenjy
  project: PredatorPrey
  mode: online
  # mode: disabled # set to 'disabled' when debugging locally
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: HideAndSeek_circle_static_UED_large_cylinder_cl_v2
  # - task: HideAndSeek_circle_eval_large
  - algo: mappo
  - _self_
